/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './components/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        canvas: '#F7F2EA',
        surface: '#FFFCF6',
        'surface-raised': '#F0E6D8',
        ink: '#171411',
        muted: '#746B60',
        faint: '#A69685',
        rule: '#E4D8C8',
        'rule-strong': '#CDBDA8',
        'focus-canvas': '#0B0E0F',
        'focus-surface': '#121819',
        'focus-rule': '#253034',
        'focus-text': '#FFF8EE',
        'focus-muted': '#9FA9A5',
        'focus-faint': '#6F7A78',

        // Legacy class aliases while screens migrate.
        'bg-primary': '#F7F2EA',
        'bg-secondary': '#FFFCF6',
        'bg-tertiary': '#F0E6D8',
        'bg-overlay': '#F0E6D8',
        'bg-focus': '#0B0E0F',
        'bg-brutalist': '#0B0E0F',
        'text-primary': '#171411',
        'text-secondary': '#746B60',
        'text-tertiary': '#A69685',
        'text-muted': '#A69685',
        'text-label': '#746B60',
        'text-dim': '#CDBDA8',
        'text-ghost': '#A69685',
        'text-inverse': '#FFFCF6',

        'accent-blue': '#4C6FFF',
        'accent-blue-light': '#6E86FF',
        'accent-success': '#2F8F5B',
        'accent-warning': '#A66A00',
        'accent-danger': '#B5442E',

        'separator': '#E4D8C8',

        'pillar-body': '#D65A31',
        'pillar-money': '#2F8F5B',
        'pillar-mind': '#4C6FFF',
        'pillar-craft': '#A66A00',
        'goal-physique': '#D65A31',
        'goal-finances': '#2F8F5B',
        'goal-skills': '#A66A00',
        'goal-mind': '#4C6FFF',

        'goal-physique-tint': 'rgba(214,90,49,0.14)',
        'goal-finances-tint': 'rgba(47,143,91,0.14)',
        'goal-skills-tint': 'rgba(166,106,0,0.14)',
        'goal-mind-tint': 'rgba(76,111,255,0.14)',
      },
      borderRadius: {
        'sm': '12px',
        'md': '18px',
        'lg': '24px',
        'xl': '32px',
        'full': '9999px',
        'cta': '9999px',
      },
      spacing: {
        '1': '4px',
        '2': '8px',
        '3': '12px',
        '4': '16px',
        '5': '20px',
        '6': '24px',
        '8': '32px',
        '10': '40px',
        '12': '48px',
      },
      fontSize: {
        'caption': ['11px', { lineHeight: '15px' }],
        'footnote': ['12px', { lineHeight: '16px' }],
        'subheadline': ['15px', { lineHeight: '21px' }],
        'callout': ['16px', { lineHeight: '22px' }],
        'body': ['17px', { lineHeight: '24px' }],
        'headline': ['17px', { lineHeight: '24px' }],
        'title3': ['20px', { lineHeight: '25px' }],
        'title2': ['24px', { lineHeight: '30px' }],
        'title1': ['34px', { lineHeight: '36px' }],
        'largeTitle': ['44px', { lineHeight: '44px' }],
        'display1': ['56px', { lineHeight: '56px' }],
        'display2': ['44px', { lineHeight: '44px' }],
        'display3': ['34px', { lineHeight: '36px' }],
        'score': ['64px', { lineHeight: '64px' }],
        'timer': ['112px', { lineHeight: '112px' }],
      },
      fontFamily: {
        serif: ['InstrumentSerif-Regular'],
        serifItalic: ['InstrumentSerif-Italic'],
        sans: ['SourceSans3-Regular'],
        sansMedium: ['SourceSans3-Medium'],
        sansSemiBold: ['SourceSans3-SemiBold'],
        sansBold: ['SourceSans3-Bold'],
        mono: ['IBMPlexMono-Regular'],
        monoMedium: ['IBMPlexMono-Medium'],
        monoSemiBold: ['IBMPlexMono-SemiBold'],
      },
    },
  },
  plugins: [],
};
